[package]
name = "sodium"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2.2.0"
napi-derive = "2.2.0"
sodiumoxide = { git = "https://github.com/devtomio/sodiumoxide" }
dryoc = { git = "https://github.com/brndnmtthws/dryoc" }

[build-dependencies]
napi-build = "1.2.1"

[profile.release]
lto = true
