[package]
name = "sodium"
version = "0.2.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2.2.0"
napi-derive = "2.2.0"
sodiumoxide = { git = "https://github.com/devtomio/sodiumoxide", rev = "8f5ce6b" }
dryoc = { git = "https://github.com/brndnmtthws/dryoc" }

[build-dependencies]
napi-build = "1.2.1"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
overflow-checks = false
debug = true
