name: Docker nightly build

on:
  push:

jobs:
  build_image:
    name: Build nodejs-rust:lts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push alpine
        uses: docker/build-push-action@v2
        with:
          file: aarch64.Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}/nodejs-rust:lts-aarch64
